export const GET_USAGE = 'GET_USAGE'
export const GET_USAGE_BY_ID_AND_TIME = 'GET_USAGE_BY_ID_AND_TIME'


export const GET_PROJECT = 'GET_PROJECT'
export const PROJECT_CHANGE = 'PROJECT_CHANGE'
export const CRATE_PROJECT = 'CRATE_PROJECT'
